logging:
  file:
    path: /logs

server:
  port: 8900
spring:
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 15
    name: common
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.31.204:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        max-wait: 5000
        min-idle: 4
    password: ''
    port: 6379
    timeout: 1000

# 自定义配置
paladin:
  shiro-cas-enabled: false
  shiro-enabled: true
  shiro:
    cas-error-url: /static/html/error_cas_500.html
    cas-protocol: CAS20_PROXY
    cas-server-login-url: http://10.1.1.123:8768/casServ/login
    cas-server-url: http://10.1.1.123:8768/casServ
    client-server-url: http://172.16.11.135:8010
  web:
    upload-dir: /file/upload/
    file-path: /file/