logging:
  level:
    com.paladin:
      common.mapper: debug
      demo.mapper: debug

server:
  port: 8011

spring:
  datasource:
    name: styx
    url: jdbc:mysql://172.16.16.125:3306/boot2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 15
  redis:
    host: 172.16.16.125
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
  thymeleaf:
    cache: false


paladin:
  shiro:
    # 详见ShiroProperties类
    # 是否开启CAS
    cas-enabled: false
    ## cas 相关设置，暂时无用
    cas-error-url: /static/html/error_cas_500.html
    cas-protocol: CAS30
    cas-server-login-url: http://58.210.169.168:9091/login
    cas-server-url: http://58.210.169.168:9091
    client-server-url: http://192.168.31.128:8010
  file:
    base-path: D:/file/
    ftp-host: 172.16.16.120
    ftp-port: 21
    ftp-username: netin
    ftp-password: 123456
    ftp-visit-host: 172.16.16.120
    ftp-visit-port: 9021
  attachment:
    # 附件最大大小（M）
    max-file-size: 10
    # 附件删除后保留时间（天）
    expire-day: 10
    # 文件清理间隔（）
    file-clean-interval: 120
  # 用户默认密码
  default-password: 123456
  # 是否使用随机缺省密码
  default-password-random: false
  generate:
    # 是否生成swagger注解
    swagger: true



# 动态数据库配置
#  dynamic-datasource-enabled: true
#  dynamic:
#    mybatis:
#      mapper-location: classpath:dynamic/mapper/**/*.xml
#      type-aliases-package: com.paladin.demo.dynamic.model
#    source[0]:
#      name: mysql1
#      url: jdbc:mysql://172.16.16.120:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#      username: netin
#      password: 123456
#    source[1]:
#      name: mysql2
#      url: jdbc:mysql://172.16.16.120:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#      username: netin
#      password: 123456