spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    date-format: com.paladin.framework.web.convert.AutoDateFormat
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
    view:
      prefix: classpath:/templates
      suffix: .html
  profiles:
    active: dev
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  # 分页合理化（解决选择一个较大页码翻页后，选择搜索条件，搜索结果为总页数为1，但是页码大于1导致不出现结果问题）
  reasonable: true
