logging:
  file:
    path: /logs
  level:
    com:
      paladin:
        common:
          mapper: debug
        demo:
          mapper: debug

server:
  port: 8011


spring:
  datasource:
    name: common
    password: ''
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000
  thymeleaf:
    cache: false


paladin:
  shiro-cas-enabled: false
  shiro-enabled: true
  shiro:
    cas-error-url: /static/html/error_cas_500.html
    cas-protocol: CAS30
    cas-server-login-url: http://58.210.169.168:9091/login
    cas-server-url: http://58.210.169.168:9091
    client-server-url: http://192.168.31.128:8010
  web:
    upload-dir: D:/file/upload/
    file-path: D:/file/
  # 动态数据库配置
  dynamic-datasource-enabled: true
  dynamic:
    mybatis:
      mapper-location: classpath:dynamic/mapper/**/*.xml
      type-aliases-package: com.paladin.demo.dynamic.model
    source[0]:
      name: mysql1
      url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
    source[1]:
      name: mysql2
      url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root